### ISSUE TITLE
Failed to launch WinUI3 project on Windows 10

### ISSUE THREAD

**Issue by nodew** [davidortinau/WeatherTwentyOne#20]
I can build WinUI3 successfully, but when I launch it with debug, I got the following exception:

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeType.CreateInstanceOfT()
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at Microsoft.UI.Xaml.Application._IApplicationStatics.get_Instance()
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
   at WeatherTwentyOne.WinUI.Program.Main(String[] args) in C:\Users\wangq\development\WeatherTwentyOne\src\WeatherTwentyOne.WinUI3\obj\x64\Debug\net6.0-windows10.0.19041\Windows\WindowsApp.g.i.cs:line 26

COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
```

Windows 10 build version: 19042.985

**Comment by Naxaliav** [comment]
Receiving same error

**Comment by Naxaliav** [comment]
**Solved**: 'Package' project has to be launched. 
![image](https://user-images.githubusercontent.com/33034058/120386625-8bba7a80-c331-11eb-8cc4-ae50ad5ac55e.png)
